# Generated by Django 5.0.6 on 2024-06-17 08:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Название статьи')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Тест статьи')),
            ],
        ),
    ]
