# Generated by Django 5.0.6 on 2024-06-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitePages', '0003_article_slug_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='images', verbose_name='Картинка в статье'),
            preserve_default=False,
        ),
    ]
