# Generated by Django 5.0.6 on 2024-06-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitePages', '0004_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('ip', models.CharField(max_length=20, verbose_name='IP')),
                ('utm_source', models.CharField(max_length=20, null=True, verbose_name='utm_source')),
                ('utm_medium', models.CharField(max_length=20, null=True, verbose_name='utm_medium')),
                ('utm_campaign', models.CharField(max_length=20, null=True, verbose_name='utm_campaign')),
                ('utm_content', models.CharField(max_length=20, null=True, verbose_name='utm_content')),
                ('utm_term', models.CharField(max_length=20, null=True, verbose_name='utm_term')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата и время заявки')),
                ('transitionSource', models.URLField(verbose_name='Источник перехода')),
                ('page', models.URLField(verbose_name='Страница заявки')),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статью', 'verbose_name_plural': 'Статьи'},
        ),
    ]
