# Generated by Django 5.0.6 on 2024-06-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitePages', '0005_client_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиента', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='client',
            name='utm_source',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='utm_source'),
        ),
    ]
