# Generated by Django 5.0.6 on 2024-06-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitePages', '0006_alter_client_options_alter_client_utm_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description_page',
            field=models.ImageField(default='', upload_to='images', verbose_name='Description страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='name_page',
            field=models.ImageField(default='', upload_to='images', verbose_name='Название страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='title_page',
            field=models.ImageField(default='', upload_to='images', verbose_name='Title страницы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='utm_campaign'),
        ),
        migrations.AlterField(
            model_name='client',
            name='utm_content',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='utm_content'),
        ),
        migrations.AlterField(
            model_name='client',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='utm_medium'),
        ),
        migrations.AlterField(
            model_name='client',
            name='utm_term',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='utm_term'),
        ),
    ]
