# Generated by Django 5.0.6 on 2024-06-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitePages', '0007_article_description_page_article_name_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description_page',
            field=models.CharField(max_length=150, verbose_name='Description страницы'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name_page',
            field=models.CharField(max_length=150, verbose_name='Название страницы'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_page',
            field=models.CharField(max_length=150, verbose_name='Title страницы'),
        ),
    ]
