# Generated by Django 5.0.6 on 2024-06-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitePages', '0008_alter_article_description_page_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
