# Generated by Django 5.0.6 on 2024-06-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitePages', '0009_delete_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
