# Generated by Django 5.0.6 on 2024-06-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('ip', models.CharField(max_length=20, verbose_name='IP')),
                ('utm_source', models.CharField(blank=True, max_length=20, null=True, verbose_name='utm_source')),
                ('utm_medium', models.CharField(blank=True, max_length=20, null=True, verbose_name='utm_medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=20, null=True, verbose_name='utm_campaign')),
                ('utm_content', models.CharField(blank=True, max_length=20, null=True, verbose_name='utm_content')),
                ('utm_term', models.CharField(blank=True, max_length=20, null=True, verbose_name='utm_term')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата и время заявки')),
                ('transitionSource', models.URLField(verbose_name='Источник перехода')),
                ('page', models.URLField(verbose_name='Страница заявки')),
            ],
            options={
                'verbose_name': 'Клиента',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
