# Generated by Django 5.0.6 on 2024-06-28 13:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Название статьи')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Контент статьи')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='images', verbose_name='Картинка в статье')),
                ('title_page', models.CharField(max_length=150, verbose_name='Title страницы')),
                ('description_page', models.CharField(max_length=150, verbose_name='Description страницы')),
                ('name_page', models.CharField(max_length=150, verbose_name='Название страницы')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
