# Generated by Django 5.0.6 on 2024-06-28 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationshook',
            options={'verbose_name': 'Ключ', 'verbose_name_plural': 'Ключи'},
        ),
        migrations.AlterModelOptions(
            name='nameintegrations',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AlterField(
            model_name='integrationshook',
            name='hook',
            field=models.CharField(max_length=350, unique=True, verbose_name='API или Хук'),
        ),
        migrations.AlterField(
            model_name='integrationshook',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.nameintegrations', verbose_name='Сервис'),
        ),
        migrations.AlterField(
            model_name='nameintegrations',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название интеграции'),
        ),
    ]
